function status = initStatus()
status = struct( ...
    'lookahead_distance', NaN, ...
    'target_bearing', NaN, ...
    'crosstrack_error', NaN, ...
    'distance_to_waypoint', NaN, ...
    'bearing_to_waypoint', NaN ...
);
end
